### ISSUE TITLE
Count should be 20?

### ISSUE THREAD

**Issue by apitts** [craigtutterow/sna-js#1]
It seems like the LinkedIn API may have changed?

In the below line, I believe count is now limited to 20 so paging would need to be implemented?

 IN.API.Raw("/people/" + connection.id + "/relation-to-viewer/related-connections?count=99")

**Comment by craigtutterow** [comment]
Thanks - this is my first comment! It's a good question. I read this on the dev forums as well, but during my initial testing I found that pagination was not needed to get more than 20 mutual connections to appear in the graph. When looking at one of my most connected colleagues' li page, I see that we share 40 contacts. When looking at the graph on the site, I see that 34 of those connections are visible. I initially chalked this up to the fact that some members opt out of making those connections visible in the privacy settings and are omitted from the graph. However, I now see that some connections are present in the graph, but are missing connections to other included contacts. 

So I think the issue is this. If a connection is listed in either person's first 20 returned contacts, that connection will appear. If the connection is listed outside of the top 20 connections for both individuals, that connection will not appear.

The issue with implementing pagination is that since each call will be counted towards the throttle limit for the day, it will decrease the number of connections that can be displayed. So I will either be sampling on the nodes or the edges due to the API constraints. 

Which do you think is preferable? Also, how do you think I should change the language on the page to reflect these constraints?

**Comment by apitts** [comment]
My suggestion would be to implement paging and take the hit on the throttle.  It's probably only a small handful of connections that have more than 20 mutual connections so we are probably talking about something like a 450+ limit rather than a 500 limit.  The actual number though will be lower the more connected someone is so someone with 5000 contacts may see less than 450 I suspect.  A bit hard to explain to users I agree.  

Some suggested wording changes, in case it's helpful:
Due to LinkedIn API restrictions, we are limited in the number of times we can display this information in a day. We are able to display up to between approximately 450 and 500 contacts per day where the actual limit depends on how connected your contacts are. Those people with more contacts than this limit, will see that the application will draw contacts up to that limit in alphabetical order. To avoid hitting this cap, please do not refresh the page, and try to limit visits to once per day. This limit resets each day at 12am UTC time, so you can always try again tomorrow. Thanks for your understanding!

**Comment by craigtutterow** [comment]
finally got around to fixing this! Thanks for raising the issue.
