### ISSUE TITLE
Some of my connections that should be connected to each other too are not

### ISSUE THREAD

**Issue by LJNielsenDk** [craigtutterow/sna-js#3]
Some of my connections that should be connected to each other too are not.

Is this a known issue? It might be a good idea to put a note about that on the page if it's not going to get fixed.

**Comment by craigtutterow** [comment]
Yes, there are false negatives because I chose not to implement pagination.
This was discussed in issue 1. I can only request 20 mutual connections at
a time per contact. There is a tradeoff between requesting connections from
additional contacts (up to 500) vs. requesting additional contacts from
someone with more than 20 connections in common. Right now, I believe the
program registers the connection if the connection is listed within the
first 20 connections of either person in the dyad (which is why some will
have more than 20 connections even though the API only allows you to fetch
20 at a time). The alternative is that I reduce the number of contacts we
get by the number of times we page through the connections results. I agree
that I should probably put a disclaimer on the page if I stick with the
current process.

**Comment by NicoChaussin** [comment]
I thought LinkedIn shut down their API. Do you still manage to retrieve contacts using the JS API?

**Comment by craigtutterow** [comment]
Added pagination to fix the issue. Thanks for reminding me of this Lars. Nico, I am adding a bit to the readme file about the API status.

**Comment by apitts** [comment]
I too am very interested to see what you add to the Readme as I had the same thought / question as @NicoChaussin!
